sudo: required
services:
  - docker
  
before_install:
  - docker build -t jasstrix/docker-react -f Dockerfile.dev .

script:
  - docker run jasstrix/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  location: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-914200995115"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"